In [86]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [45]:
df = pd.read_excel('Data Makro Coba Regresi.xlsx')
df

,No,Inflasi,Kurs Dollar,Tingkat Pengangguran Terbuka,Penduduk Bekerja,PDB,BI-7Day-RR,Kurs Jual,Kurs Beli,Kurs_Tengh,...,Ketersediaanlapangan kerja,Indeks Ekspektasi Kegiatan Usaha,Bucket1,Bucket2,Bucket3,Bucket4,Bucket5,Bucket6,Bucket7,ENR_SA
0,2,6.29,12863,5.81,94.19,2728180.7,NaN,12927.00,12799.00,12863.000,...,93.500000,127.700000,0.091049,0.090332,0.645989,2.127202,0.762545,0.364279,0.700995,3.916049e+06
1,3,6.38,13084,5.81,94.19,2728180.7,NaN,13149.00,13019.00,13084.000,...,94.200000,126.300000,0.111084,0.125652,0.330993,1.357395,1.071865,0.539643,0.815069,3.928442e+06
2,4,6.79,12937,5.81,94.19,2867948.4,NaN,13002.00,12872.00,12937.000,...,86.900000,114.100000,0.127906,0.062510,0.360759,1.041908,0.883360,1.113973,0.868535,3.927886e+06
3,5,7.15,13332,5.81,94.19,2867948.4,NaN,13277.00,13145.00,13211.000,...,85.700000,123.800000,0.109887,0.067848,0.497617,1.740524,2.200627,0.919161,0.248662,3.987756e+06
4,6,7.26,13481,5.81,94.19,2867948.4,NaN,13399.00,13265.00,13332.000,...,83.700000,122.200000,0.134203,0.082354,0.254064,3.272908,0.758081,1.153567,0.284666,4.283802e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,92,4.69,14853,5.86,94.14,5091171.0,3.75,14949.38,14800.63,14875.005,...,112.494544,144.144259,0.049760,0.157801,0.162716,0.434568,0.692453,0.762326,0.983289,6.017576e+06
91,93,5.95,15232,5.86,94.14,5091171.0,4.25,15323.24,15170.76,15247.000,...,113.579981,119.113809,0.050906,0.103523,0.183221,0.378696,0.786703,0.870500,0.641438,6.038004e+06
92,94,5.71,15596,5.86,94.14,5091171.0,4.75,15619.71,15464.29,15542.000,...,112.919812,126.698386,0.045186,0.180939,0.382687,0.449638,0.712818,0.964153,0.861091,6.051226e+06
93,95,5.42,15742,5.86,94.14,5091171.0,5.25,15815.68,15658.32,15737.000,...,113.852004,120.270473,0.049941,0.077355,0.200882,0.413168,0.602800,0.800413,0.821972,6.015487e+06
94,96,5.51,15592,5.86,94.14,5091171.0,5.50,15809.66,15652.34,15731.000,...,116.495091,131.113100,0.046481,0.181614,0.474894,0.564434,0.830290,0.981003,1.290027,7.111068e+06

In [46]:
df.describe()

,No,Inflasi,Kurs Dollar,Tingkat Pengangguran Terbuka,Penduduk Bekerja,PDB,BI-7Day-RR,Kurs Jual,Kurs Beli,Kurs_Tengh,...,Ketersediaanlapangan kerja,Indeks Ekspektasi Kegiatan Usaha,Bucket1,Bucket2,Bucket3,Bucket4,Bucket5,Bucket6,Bucket7,ENR_SA
count,95.000000,95.000000,95.000000,95.000000,95.000000,9.500000e+01,81.000000,95.000000,95.000000,95.000000,...,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,9.500000e+01
mean,49.000000,3.432105,14070.252632,5.685053,94.314947,3.767529e+06,4.577160,14144.277368,14003.513684,14073.895526,...,85.267016,127.911172,0.095562,0.153831,0.313207,0.859003,0.728274,1.030313,0.799341,6.149180e+06
std,27.568098,1.516052,685.188559,0.573550,0.573550,6.197132e+05,0.829761,690.748280,683.905198,687.326703,...,23.995918,13.107905,0.028365,0.058999,0.100145,0.639094,0.250772,0.674837,0.337639,1.051972e+06
min,2.000000,1.320000,12863.000000,4.940000,92.930000,2.728181e+06,3.500000,12927.000000,12799.000000,12863.000000,...,17.144825,86.942136,0.045186,0.062510,0.124612,0.378696,0.230124,0.285307,0.149314,3.916049e+06
25%,25.500000,2.605000,13458.500000,5.265000,93.980000,3.228172e+06,3.750000,13553.500000,13419.500000,13486.500000,...,76.450000,121.653666,0.075039,0.111294,0.241747,0.541285,0.620324,0.706562,0.615976,5.681316e+06
50%,49.000000,3.250000,14105.000000,5.500000,94.500000,3.799214e+06,4.750000,14175.530000,14034.480000,14105.005000,...,91.400000,128.949006,0.093040,0.140753,0.302062,0.684094,0.707552,0.835887,0.831388,6.335970e+06
75%,72.500000,3.855000,14457.500000,6.020000,94.735000,4.042982e+06,5.250000,14515.215000,14370.785000,14443.000000,...,101.385025,135.875993,0.113457,0.182745,0.380623,0.836702,0.798201,1.044151,0.956268,6.935118e+06
max,96.000000,7.260000,16367.000000,7.070000,95.060000,5.091171e+06,6.000000,16448.840000,16285.170000,16367.005000,...,121.449425,153.340933,0.169274,0.316128,0.645989,3.824938,2.200627,3.957020,2.156443,7.920750e+06

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 27 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   No                                              95 non-null     int64
 1   Inflasi                                         95 non-null     float64
 2   Kurs Dollar                                     95 non-null     int64
 3   Tingkat Pengangguran Terbuka                    95 non-null     float64
 4   Penduduk Bekerja                                95 non-null     float64
 5   PDB                                             95 non-null     float64
 6   BI-7Day-RR                                      81 non-null     float64
 7   Kurs Jual                                       95 non-null     float64
 8   Kurs Beli                                       95 non-null     float64
 9   Kurs_Tengh                                      95 non-null     float64
 10  Indeks Keyakinan Konsumen (IKK)                 95 non-null     float64
 11  Indeks Kondisi Ekonomi Saat Ini (IKE)           95 non-null     float64
 12  Pengeluaran >Rp5 juta(IKK)                      95 non-null     float64
 13  Pengeluaran >Rp5 juta(IKE)                      95 non-null     float64
 14  Pengeluaran >Rp5 juta(IEK)                      95 non-null     float64
 15  Indeks Penghasilan Saat Ini(Pengeluaran >5 Jt)  95 non-null     float64
 16  Indeks Pembelian Barang tahan lama              95 non-null     float64
 17  Ketersediaanlapangan kerja                      95 non-null     float64
 18  Indeks Ekspektasi Kegiatan Usaha                95 non-null     float64
 19  Bucket1                                         95 non-null     float64
 20  Bucket2                                         95 non-null     float64
 21  Bucket3                                         95 non-null     float64
 22  Bucket4                                         95 non-null     float64
 23  Bucket5                                         95 non-null     float64
 24  Bucket6                                         95 non-null     float64
 25  Bucket7                                         95 non-null     float64
 26  ENR_SA                                          95 non-null     float64
dtypes: float64(25), int64(2)
memory usage: 20.2 KB

In [48]:
# fill missing value in BI-7Day-RR with mean

df['BI-7Day-RR'] = df['BI-7Day-RR'].fillna(df['BI-7Day-RR'].mean())

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 27 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   No                                              95 non-null     int64
 1   Inflasi                                         95 non-null     float64
 2   Kurs Dollar                                     95 non-null     int64
 3   Tingkat Pengangguran Terbuka                    95 non-null     float64
 4   Penduduk Bekerja                                95 non-null     float64
 5   PDB                                             95 non-null     float64
 6   BI-7Day-RR                                      95 non-null     float64
 7   Kurs Jual                                       95 non-null     float64
 8   Kurs Beli                                       95 non-null     float64
 9   Kurs_Tengh                                      95 non-null     float64
 10  Indeks Keyakinan Konsumen (IKK)                 95 non-null     float64
 11  Indeks Kondisi Ekonomi Saat Ini (IKE)           95 non-null     float64
 12  Pengeluaran >Rp5 juta(IKK)                      95 non-null     float64
 13  Pengeluaran >Rp5 juta(IKE)                      95 non-null     float64
 14  Pengeluaran >Rp5 juta(IEK)                      95 non-null     float64
 15  Indeks Penghasilan Saat Ini(Pengeluaran >5 Jt)  95 non-null     float64
 16  Indeks Pembelian Barang tahan lama              95 non-null     float64
 17  Ketersediaanlapangan kerja                      95 non-null     float64
 18  Indeks Ekspektasi Kegiatan Usaha                95 non-null     float64
 19  Bucket1                                         95 non-null     float64
 20  Bucket2                                         95 non-null     float64
 21  Bucket3                                         95 non-null     float64
 22  Bucket4                                         95 non-null     float64
 23  Bucket5                                         95 non-null     float64
 24  Bucket6                                         95 non-null     float64
 25  Bucket7                                         95 non-null     float64
 26  ENR_SA                                          95 non-null     float64
dtypes: float64(25), int64(2)
memory usage: 20.2 KB

In [50]:
df

,No,Inflasi,Kurs Dollar,Tingkat Pengangguran Terbuka,Penduduk Bekerja,PDB,BI-7Day-RR,Kurs Jual,Kurs Beli,Kurs_Tengh,...,Ketersediaanlapangan kerja,Indeks Ekspektasi Kegiatan Usaha,Bucket1,Bucket2,Bucket3,Bucket4,Bucket5,Bucket6,Bucket7,ENR_SA
0,2,6.29,12863,5.81,94.19,2728180.7,4.57716,12927.00,12799.00,12863.000,...,93.500000,127.700000,0.091049,0.090332,0.645989,2.127202,0.762545,0.364279,0.700995,3.916049e+06
1,3,6.38,13084,5.81,94.19,2728180.7,4.57716,13149.00,13019.00,13084.000,...,94.200000,126.300000,0.111084,0.125652,0.330993,1.357395,1.071865,0.539643,0.815069,3.928442e+06
2,4,6.79,12937,5.81,94.19,2867948.4,4.57716,13002.00,12872.00,12937.000,...,86.900000,114.100000,0.127906,0.062510,0.360759,1.041908,0.883360,1.113973,0.868535,3.927886e+06
3,5,7.15,13332,5.81,94.19,2867948.4,4.57716,13277.00,13145.00,13211.000,...,85.700000,123.800000,0.109887,0.067848,0.497617,1.740524,2.200627,0.919161,0.248662,3.987756e+06
4,6,7.26,13481,5.81,94.19,2867948.4,4.57716,13399.00,13265.00,13332.000,...,83.700000,122.200000,0.134203,0.082354,0.254064,3.272908,0.758081,1.153567,0.284666,4.283802e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,92,4.69,14853,5.86,94.14,5091171.0,3.75000,14949.38,14800.63,14875.005,...,112.494544,144.144259,0.049760,0.157801,0.162716,0.434568,0.692453,0.762326,0.983289,6.017576e+06
91,93,5.95,15232,5.86,94.14,5091171.0,4.25000,15323.24,15170.76,15247.000,...,113.579981,119.113809,0.050906,0.103523,0.183221,0.378696,0.786703,0.870500,0.641438,6.038004e+06
92,94,5.71,15596,5.86,94.14,5091171.0,4.75000,15619.71,15464.29,15542.000,...,112.919812,126.698386,0.045186,0.180939,0.382687,0.449638,0.712818,0.964153,0.861091,6.051226e+06
93,95,5.42,15742,5.86,94.14,5091171.0,5.25000,15815.68,15658.32,15737.000,...,113.852004,120.270473,0.049941,0.077355,0.200882,0.413168,0.602800,0.800413,0.821972,6.015487e+06
94,96,5.51,15592,5.86,94.14,5091171.0,5.50000,15809.66,15652.34,15731.000,...,116.495091,131.113100,0.046481,0.181614,0.474894,0.564434,0.830290,0.981003,1.290027,7.111068e+06

In [58]:
df = df.drop(['No'], axis=1)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 26 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Inflasi                                         95 non-null     float64
 1   Kurs Dollar                                     95 non-null     int64
 2   Tingkat Pengangguran Terbuka                    95 non-null     float64
 3   Penduduk Bekerja                                95 non-null     float64
 4   PDB                                             95 non-null     float64
 5   BI-7Day-RR                                      95 non-null     float64
 6   Kurs Jual                                       95 non-null     float64
 7   Kurs Beli                                       95 non-null     float64
 8   Kurs_Tengh                                      95 non-null     float64
 9   Indeks Keyakinan Konsumen (IKK)                 95 non-null     float64
 10  Indeks Kondisi Ekonomi Saat Ini (IKE)           95 non-null     float64
 11  Pengeluaran >Rp5 juta(IKK)                      95 non-null     float64
 12  Pengeluaran >Rp5 juta(IKE)                      95 non-null     float64
 13  Pengeluaran >Rp5 juta(IEK)                      95 non-null     float64
 14  Indeks Penghasilan Saat Ini(Pengeluaran >5 Jt)  95 non-null     float64
 15  Indeks Pembelian Barang tahan lama              95 non-null     float64
 16  Ketersediaanlapangan kerja                      95 non-null     float64
 17  Indeks Ekspektasi Kegiatan Usaha                95 non-null     float64
 18  Bucket1                                         95 non-null     float64
 19  Bucket2                                         95 non-null     float64
 20  Bucket3                                         95 non-null     float64
 21  Bucket4                                         95 non-null     float64
 22  Bucket5                                         95 non-null     float64
 23  Bucket6                                         95 non-null     float64
 24  Bucket7                                         95 non-null     float64
 25  ENR_SA                                          95 non-null     float64
dtypes: float64(25), int64(1)
memory usage: 19.4 KB

In [61]:
features = df.columns[0:24]
target = df.columns[-1]

X = df[features].values
y = df[target].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [79]:
# X_train.shape
X_test.shape

(29, 24)

In [62]:
# Pre-Processing using Standard Scaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

LINEAR REGRESSION

In [81]:
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)
y_pred

array([7136046.96969822, 7316270.96969822, 6538030.96969822,
       7062318.96969822, 6996782.96969822, 5995310.96969822,
       4600622.96969822, 6783790.96969822, 6259502.96969822,
       5853998.96969822, 6980398.96969822, 6142766.96969822,
       5493550.96969822, 6215470.96969822, 6134574.96969822,
       6038318.96969822, 5104430.96969822, 5849902.96969822,
       5888814.96969822, 6388526.96969822, 6867758.96969822,
       3805998.96969822, 6767406.96969822, 6783790.96969822,
       5767982.96969822, 5956398.96969822, 6619950.96969822,
       4956974.96969822, 6021934.96969822])

In [90]:
# RMSE

rmse = mean_squared_error(y_test, y_pred, squared=False)
print("RMSE of Linear Regression: {}".format(rmse))

# R2 Score
r2 = r2_score(y_test, y_pred)
print("R2 Score of Linear Regression: {}".format(r2))

RMSE of Linear Regression: 614376.812206096
R2 Score of Linear Regression: 0.5793381310974184

RIDGE REGRESSION

In [93]:
ridge_model = Ridge(alpha=10)
ridge_model.fit(X_train, y_train)

y_pred_ridge = ridge_model.predict(X_test)
y_pred_ridge

array([6560672.10248845, 6464979.39462397, 6859819.3556772 ,
       6751136.92251483, 6925827.07436312, 5840090.73465819,
       5556509.66679271, 6775889.68059151, 5717922.94042794,
       6084190.46516442, 6652180.07810131, 6325070.38210615,
       5769051.81157373, 6281228.32083498, 5856643.6807895 ,
       5718795.88233581, 5536891.69996306, 6216835.6157952 ,
       6236521.24037933, 6337788.4620781 , 6394945.97675003,
       5247936.14931275, 6897413.67079733, 5888625.84665061,
       5766761.07663138, 6171459.60486133, 3906301.05287988,
       5692263.41250148, 5887235.85833177])

In [94]:
# RMSE

rmse = mean_squared_error(y_test, y_pred_ridge, squared=False)
print("RMSE of Ridge Regression: {}".format(rmse))

# R2 Score
r2 = r2_score(y_test, y_pred_ridge)
print("R2 Score of Ridge Regression: {}".format(r2))

RMSE of Ridge Regression: 635005.5250989384
R2 Score of Ridge Regression: 0.550615051086067

LASSO REGRESSION

In [100]:
lasso_model = Lasso(alpha=10, max_iter=1000)
lasso_model.fit(X_train, y_train)

y_pred_lasso = lasso_model.predict(X_test)
y_pred_lasso

c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.180e+12, tolerance: 7.741e+09
  model = cd_fast.enet_coordinate_descent(

array([6720385.94939397, 6668411.78959718, 6903854.90499986,
       6962140.78176512, 7267790.72565619, 6348583.26864261,
       5496992.13553927, 6454101.60209876, 6382261.23728161,
       5724338.78511407, 6878551.64955224, 6181768.43847707,
       5927476.11146422, 6290881.47885465, 5862533.08350978,
       5693157.48177133, 5324556.48547344, 5946663.29275603,
       6154417.04843435, 6021360.75217652, 7244884.64111331,
       4736364.72286715, 7178368.02154661, 6937738.67309646,
       6181086.1928252 , 5940138.1909956 , 4585270.51889288,
       5768604.08474708, 5751406.91733201])

In [101]:
# RMSE

rmse = mean_squared_error(y_test, y_pred_lasso, squared=False)
print("RMSE of Lasso Regression: {}".format(rmse))

# R2 Score
r2 = r2_score(y_test, y_pred_lasso)
print("R2 Score of Lasso Regression: {}".format(r2))

RMSE of Lasso Regression: 558244.9114956303
R2 Score of Lasso Regression: 0.652693380576335